oc_platform_home:
    path:      /{page}
    defaults:  
        _controller: OCPlatBundle:Advert:index
        pages:    1
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: OCPlatBundle:Advert:view }
    requirements:
        id: \d+

oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: OCPlatBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml

oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatBundle:Advert:add }

oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatBundle:Advert:add }

oc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatBundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatBundle:Advert:delete }
    requirements:
        id: \d+